### ISSUE TITLE
Please help me 

### ISSUE THREAD

**Issue by xiaonian233** [rutkai/Mjolnir-Authentication-Server#2]
When I run "NODE_ENV=production node app.js"
![image](https://user-images.githubusercontent.com/21072615/42223502-7faf4fe0-7f0a-11e8-9db3-ff46ff1648f4.png)

**Comment by xiaonian233** [comment]
node-v8.11.3-linux-x64

**Comment by xiaonian233** [comment]
Guy,I solved the problem,but another appeard 
![image](https://user-images.githubusercontent.com/21072615/42322817-76db5c60-8090-11e8-880a-7979844ae4db.png)
Only ip like(127.0.0.1:9010) work,I can't use domain,I Configured apache you can directly access https://sessionserver.whitedew.top/session/minecraft/join and hasjoined

I use IP,but skin and cape can use domain load
![image](https://user-images.githubusercontent.com/21072615/42322909-cd45bca8-8090-11e8-80c8-93f1da656251.png)
Please help me

**Comment by rutkai** [comment]
I suppose you managed to solve the issue. BTW I updated the sources so feel free to pull the changes and update your packages. It may help with newer node version.

**Comment by xiaonian233** [comment]
ok,thx
